"""This is a list of dictionaries and each entry is a different Pokemon
"""

pokelist = [{'name': 'Bulbasaur', 'ID': '#001', 'type': ('grass', 'poison'), 'HP': 40, 'attack': 49, 'defense': 39,
            "weight(kg)": 6.5},
        {'name': 'Ivysaur', 'ID': '#002', 'type': ('grass', 'poison'), 'HP': 60, 'attack': 61, 'defense': 49,
            "weight(kg)": 13},
        {'name': 'Venusaur', 'ID': '#003', 'type': ('grass', 'poison'), 'HP': 75, 'attack': 67, 'defense': 56,
            "weight(kg)": 100},
        {'name': 'Charmander', 'ID': '#004', 'type': 'fire', 'HP': 39, 'attack': 52, 'defense': 43,
            "weight(kg)": 8.5},
        {'name': 'Charmeleon', 'ID': '#005', 'type': 'fire', 'HP': 58, 'attack': 64, 'defense': 58,
            "weight(kg)": 19},
        {'name': 'Charizard', 'ID': '#006', 'type': ('fire', 'flying'), 'HP': 78, 'attack': 84, 'defense': 78,
            "weight(kg)": 90},
        {'name': 'Squirtle', 'ID': '#007', 'type': 'water', 'HP': 44, 'attack': 48, 'defense': 65,
            "weight(kg)": 9},
        {'name': 'Wartortle', 'ID': '#008', 'type': 'water', 'HP': 59, 'attack': 63, 'defense': 80,
            "weight(kg)": 22},
        {'name': 'Blastoise', 'ID': '#009', 'type': 'water', 'HP': 79, 'attack': 83, 'defense': 100,
            "weight(kg)": 85},
        {'name': 'Caterpie', 'ID': '#010', 'type': 'bug', 'HP': 45, 'attack': 30, 'defense': 35,
            "weight(kg)": 3},
        {'name': 'Metapod', 'ID': '#011', 'type': 'bug', 'HP': 50, 'attack': 20, 'defense': 55,
            "weight(kg)": 10},
        {'name': 'Butterfree', 'ID': '#012', 'type': ('bug', 'flying'), 'HP': 60, 'attack': 45, 'defense': 50,
            "weight(kg)": 32},
        {'name': 'Weedle', 'ID': '#013', 'type': ('bug', 'poison'), 'HP': 40, 'attack': 35, 'defense': 30,
            "weight(kg)": 3.2},
        {'name': 'Kakuna', 'ID': '#014', 'type': ('bug', 'poison'), 'HP': 45, 'attack': 25, 'defense': 50,
            "weight(kg)": 10},
        {'name': 'Beedrill', 'ID': '#015', 'type': ('bug', 'poison'), 'HP': 65, 'attack': 90, 'defense': 40,
            "weight(kg)": 30},
        {'name': 'Pidgey', 'ID': '#016', 'type': ('normal', 'flying'), 'HP': 40, 'attack': 45, 'defense': 40,
            "weight(kg)": 2},
        {'name': 'Pidgeotto', 'ID': '#017', 'type': ('normal', 'flying'), 'HP': 63, 'attack': 60, 'defense': 55,
            "weight(kg)": 30},
        {'name': 'Pidgeot', 'ID': '#018', 'type': ('flying', 'normal'), 'HP': 83, 'attack': 80, 'defense': 75,
            "weight(kg)": 40},
        {'name': 'Rattata', 'ID': '#019', 'type': 'normal', 'HP': 30, 'attack': 56, 'defense': 35,
            "weight(kg)": 3.5},



        ]
